w10d01/dog-app/config/routes.rb
Rails.application.routes.draw do
  resources :favourites
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # get 'login', action: :index, controller: 'users'
  # get 'login', to: 'users#index'

  # resources :breeds
  # resources :dogs

  # breeds/2/dogs
  resources :breeds do
    resources :dogs
  end
end

w10d01/dog-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

w10d01/dog-app/app/models/breed.rb
class Breed < ApplicationRecord
  has_many :dogs # breed.dogs()
end

w10d01/dog-app/app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :breed # dog.breed()
end

w10d01/dog-app/app/models/favourite.rb
class Favourite < ApplicationRecord
end

w10d01/dog-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

w10d01/dog-app/app/controllers/breeds_controller.rb
class BreedsController < ApplicationController
  def index
    @breeds = Breed.all()
  end
end

w10d01/dog-app/app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    breed_id = params[:breed_id] # req.params.breed_id
    @breed = Breed.find(breed_id)

    # @all_dogs = Dog.all()

    @dogs = @breed.dogs()

    render json: {
      breed: @breed,
      dogs: @dogs
    }
  end
end

w10d01/dog-app/app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_action :set_favourite, only: %i[ show edit update destroy ]

  # GET /favourites or /favourites.json
  def index
    @favourites = Favourite.all
  end

  # GET /favourites/1 or /favourites/1.json
  def show
  end

  # GET /favourites/new
  def new
    @favourite = Favourite.new
  end

  # GET /favourites/1/edit
  def edit
  end

  # POST /favourites or /favourites.json
  def create
    @favourite = Favourite.new(favourite_params)

    respond_to do |format|
      if @favourite.save
        format.html { redirect_to favourite_url(@favourite), notice: "Favourite was successfully created." }
        format.json { render :show, status: :created, location: @favourite }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @favourite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favourites/1 or /favourites/1.json
  def update
    respond_to do |format|
      if @favourite.update(favourite_params)
        format.html { redirect_to favourite_url(@favourite), notice: "Favourite was successfully updated." }
        format.json { render :show, status: :ok, location: @favourite }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @favourite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favourites/1 or /favourites/1.json
  def destroy
    @favourite.destroy

    respond_to do |format|
      format.html { redirect_to favourites_url, notice: "Favourite was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favourite
      @favourite = Favourite.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def favourite_params
      params.fetch(:favourite, {})
    end
end

w10d01/dog-app/app/helpers/application_helper.rb
module ApplicationHelper
end

w10d01/dog-app/app/helpers/breeds_helper.rb
module BreedsHelper
end

w10d01/dog-app/app/helpers/dogs_helper.rb
module DogsHelper
end

w10d01/dog-app/app/helpers/favourites_helper.rb
module FavouritesHelper
end

w10d01/dog-app/app/views/breeds/index.html.erb
<h1>All the breeds!</h1>

<% @breeds.each do |breed| %>
  <div class="breed">
    <h2>Breed: <%= breed.breed %></h2>
    <%= link_to 'visit the dogs', breed_dogs_path(breed.id) %>
  </div>
<% end %>

w10d01/dog-app/app/views/dogs/index.html.erb
<h1>All the dogs from breed <%= @breed.breed %>!</h1>

<%= link_to 'see the breeds', breeds_path %>

<% @dogs.each do |dog| %>
  <div class="dog">
    <h2>Name: <%= dog.name %></h2>
    <h2>Sound: <%= dog.sound %></h2>
    <h2>Age: <%= dog.age %></h2>
    <h2>Size: <%= dog.size %></h2>
    <h2>Breed: <%= dog.breed.breed %></h2>
  </div>
<% end %>

w10d01/dog-app/app/views/favourites/_form.html.erb
<%= form_with(model: favourite) do |form| %>
  <% if favourite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favourite.errors.count, "error") %> prohibited this favourite from being saved:</h2>

      <ul>
        <% favourite.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

w10d01/dog-app/app/views/favourites/edit.html.erb
<h1>Editing Favourite</h1>

<%= render 'form', favourite: @favourite %>

<%= link_to 'Show', @favourite %> |
<%= link_to 'Back', favourites_path %>

w10d01/dog-app/app/views/favourites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Favourites</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favourites.each do |favourite| %>
      <tr>
        <td><%= link_to 'Show', favourite %></td>
        <td><%= link_to 'Edit', edit_favourite_path(favourite) %></td>
        <td><%= link_to 'Destroy', favourite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favourite', new_favourite_path %>

w10d01/dog-app/app/views/favourites/new.html.erb
<h1>New Favourite</h1>

<%= render 'form', favourite: @favourite %>

<%= link_to 'Back', favourites_path %>

w10d01/dog-app/app/views/favourites/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_favourite_path(@favourite) %> |
<%= link_to 'Back', favourites_path %>

w10d01/dog-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dogs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>